GAME_LEVELS = [
  ["                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "       o      o     o             o     o    o            o    o    o            ",
   " @                                                                               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxx           ",
   "                          x!!!!!x               x!!!!!!!x                        ",
   "                          x!!!!!x               x!!!!!!!x                        ",
   "                           xxxxx                 xxxvxxx                         ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                             o           o    o              o   ",
   "                                                                                 ",
   "                                         xxxxxxxxxx     xxxxxxxxxx       xxxxxxxx",],
  ["                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "            o         o         o            o           o           o           ",
   "                                                                                 ",
   "o         xxxxx    xxxxxx    xxxxxxx     xxxxxxx     xxxxxxx      xxxxxx        x",
   "                                                                                 ",
   "xxx        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
   "          vxxxxxxxvxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxvxxxxxxxxxxxxv    ",
   "  o   xx                                                                         ",
   "                                                                            o    ",
   " xxxx                                                                            ",
   "                                                                 xxxxxxxxxxxxxxxx",
   "         xxxxx                                                                   ",
   "                                                                                 ",
   "                   xxxx         o                 o     o      o                 ",
   "                                                                                 ",
   "                            xxxxxxx               x     x      x                 ",
   "                        o                                                        ",
   "                   o                                                             ",
   "                     xxxxx                                                       ",
   "            o     xxx                                                            ",
   "               xxx                          o                                    ",
   "           xxxx                                                                  ",
   "   @    xxx                                 x                                    ",
   "xxxxxxxx                                                                         ",]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
